services:
  database:
    container_name: postgres_library_container
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - '${DATABASE_PORT}:5432'
    restart: unless-stopped
